export const ADD_TODO = 'add_todo'
export const TOGGLE_TODO = 'toggle_todo'
export const SET_CUR_GROUP = 'set_cur_group'
export const CHANGE_GROUP = 'change_group'
export const UPDATE_TODO = 'update_todo'
export const DELETE_TODO = 'delete_todo'
